name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
env:
  SEGRES: src/Segres/Segres.csproj
  SEGRES_ABSTRACTIONS: src/Segres.Abstractions/Segres.Abstractions.csproj
  SEGRES_ASPNETCORE: src/Segres.AspNetCore/Segres.AspNetCore.csproj
      
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 7.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Restore
        run: dotnet restore ${{ env.SEGRES }}
      
      - name: Build
        run: dotnet build ${{ env.SEGRES }} --configuration Release --no-restore
        
      - name: Test
        run: dotnet test ${{ env.SEGRES }} --configuration Release --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:Threshold=65

      - name: Restore
        run: dotnet restore ${{ env.SEGRES_ABSTRACTIONS }}

      - name: Build
        run: dotnet build ${{ env.SEGRES_ABSTRACTIONS }} --configuration Release --no-restore

#      - name: Test
#        run: dotnet test ${{ env.SEGRES_ABSTRACTIONS }} --configuration Release --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:Threshold=65

      - name: Restore
        run: dotnet restore ${{ env.SEGRES_ASPNETCORE }}

      - name: Build
        run: dotnet build ${{ env.SEGRES_ASPNETCORE }} --configuration Release --no-restore

#      - name: Test
#        run: dotnet test ${{ env.SEGRES_ABSTRACTIONS }} --configuration Release --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:Threshold=65
