name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
env:
  PROJECT_PATH: src/Segres/Segres.csproj
      
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 3.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}
      
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore
        
      - name: Test
        run: dotnet test ${{ env.PROJECT_PATH }} --configuration Release --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:Threshold=65

