name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
      preview:
        description: 'Preview'
        required: false
        type: boolean

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
#  NUGET_SOURCE_URL: <TODO>

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-restore --no-build /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:Threshold=65

      - name: Set VERSION variable 
        run: if [ $IS_PREVIEW == true ]; then echo "VERSION=$PACKAGE_VERSION-preview" >> $GITHUB_ENV; else echo "VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV; fi
        env:
          PACKAGE_VERSION: ${{ inputs.version }}
          IS_PREVIEW: ${{ inputs.preview }}

      - name: Pack
        run: dotnet pack src/Segres/Segres.csproj --configuration Release --no-restore --no-build --include-symbols /p:Version=${VERSION} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

#      - name: Push 
#        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}