name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  SEGRES: src/Segres/Segres.csproj
  SEGRES_ABSTRACTIONS: src/Segres.Abstractions/Segres.Abstractions.csproj
  SEGRES_ASPNETCORE: src/Segres.AspNetCore/Segres.AspNetCore.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-restore --no-build /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:Threshold=20

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Pack
        run: dotnet pack ${env.SEGRES} --configuration Release --no-restore --no-build --include-symbols /p:Version=${VERSION} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
      
      - name: Pack
        run: dotnet pack ${env.SEGRES_ABSTRACTIONS} --configuration Release --no-restore --no-build --include-symbols /p:Version=${VERSION} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
      
      - name: Pack
        run: dotnet pack ${env.SEGRES_ASPNETCORE} --configuration Release --no-restore --no-build --include-symbols /p:Version=${VERSION} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
      
      - name: Push
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}